# ~n+3, n+6, n+9 mo for a given date
name: Offsets_Timeseries
run-name: ${{ inputs.year }}  ${{ inputs.burstId }} ${{ inputs.polarization }} ${{ inputs.looks }} ${{ inputs.npairs }} 

on:
  workflow_dispatch:
    inputs:
      burstId:
        type: string
        required: true
        description: ESA Burst Identifier (RelativeObit, ID, Subswath)
        default: '012_023790_IW1'
      polarization:
        type: choice
        required: true
        description: Polarization
        default: 'VV'
        options: ['VV', 'VH', 'HH']
      dt:
        type: string
        required: true
        description: Offset separation in number of years
        default: '8'
      looks:
        type: choice
        required: true
        description: Range x Azimuth Looks
        default: '20x4'
        options: ['20x4','10x2','5x1']


# Convert inputs to environment variables for all job steps
env:
  BurstId: ${{ inputs.burstId }}
  Polarization: ${{ inputs.polarization }}
  Looks: ${{ inputs.looks }}
  Offsets_DT: ${{ inputs.dt }}


jobs:
  searchASF:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      BURST_IDS: ${{ steps.asf-search.outputs.BURST_IDS }}
      MATRIX: ${{ steps.asf-search.outputs.MATRIX_PARAMS_COMBINATIONS }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      # Call python script that sets needed environment variables for next job
      - name: Search ASF for bursts
        id: asf-search
        run: | 
          python scripts/getBurstPairs.py


  hyp3-isce2:
    needs: searchASF
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.searchASF.outputs.MATRIX) }}
    uses: ./.github/workflows/offsets_pair.yml
    with:
      reference: ${{ matrix.reference }}
      secondary: ${{ matrix.secondary }} 
      burstId: ${{ inputs.burstId }}
      year: ${{ matrix.year }}
      polarization: ${{ inputs.polarization }}
      looks: ${{ inputs.looks }}
      jobname: ${{ matrix.name }}
    secrets: inherit