# Try resuable workflow pipeline for 256+ offset pairs
name: Offsets_Pipeline
run-name: ${{ inputs.burstId }} ${{ inputs.polarization }} ${{ inputs.looks }}

on:
  workflow_dispatch:
    inputs:
      burstId:
          type: string
          required: true
          description: ESA Burst Identifier (RelativeObit, ID, Subswath)
          default: '012_023790_IW1'
      polarization:
          type: choice
          required: true
          description: Polarization
          default: 'VV'
          options: ['VV', 'VH', 'HH']
      looks:
          type: choice
          required: true
          description: Range x Azimuth Looks
          default: '20x4'
          options: ['20x4','10x2','5x1']

jobs:
    denseOffsets:   
        strategy:
          fail-fast: false
          matrix: 
            dt: [4, 5, 6]
        uses: ./.github/workflows/offsets_timeseries.yml
        with: 
            burstId: ${{ inputs.burstId }}
            polarization: ${{ inputs.polarization }}
            looks: ${{ inputs.looks }}
            dt: ${{ matrix.dt }}
        secrets: inherit
