# Try resuable workflow pipeline for 256+ offset pairs
name: Offsets_Pipeline
run-name: ${{ inputs.burstId }} ${{ inputs.polarization }} ${{ inputs.looks }}

on:
  workflow_dispatch:
    inputs:
      burstId:
          type: string
          required: true
          description: ESA Burst Identifier (RelativeObit, ID, Subswath)
          default: '012_023790_IW1'
      polarization:
          type: choice
          required: true
          description: Polarization
          default: 'VV'
          options: ['VV', 'VH', 'HH']
      looks:
          type: choice
          required: true
          description: Range x Azimuth Looks
          default: '20x4'
          options: ['20x4','10x2','5x1']

jobs:
    # TODO: switch to matrix job (see insar_timeseries.yml)
    denseOffsets3:
        uses: ./.github/workflows/offsets_timeseries.yml
        with: 
            burstId: ${{ inputs.burstId }}
            polarization: ${{ inputs.polarization }}
            nlooks: ${{ inputs.looks }}
            dt: 3
        secrets: inherit
    denseOffsets6:
        uses: ./.github/workflows/offsets_timeseries.yml
        with: 
            burstId: ${{ inputs.burstId }}
            polarization: ${{ inputs.polarization }}
            nlooks: ${{ inputs.looks }}
            dt: 6
        secrets: inherit
    denseOffsets8:
        uses: ./.github/workflows/offsets_timeseries.yml
        with: 
            burstId: ${{ inputs.burstId }}
            polarization: ${{ inputs.polarization }}
            nlooks: ${{ inputs.looks }}
            dt: 8
        secrets: inherit