name: SingleBurstDenseOffsets

on:
  workflow_dispatch:
    inputs:
      reference:
        type: string
        required: true
        description: Reference Burst
        default: S1_023790_IW1_20230621T121426_VV_BAD8-BURST
      secondary:
        type: string
        required: true
        description: Secondary Burst
        default: S1_023790_IW1_20231218T121430_VV_B9A6-BURST
      nlooks:
          type: choice
          required: true
          description: Range x Azimuth Looks
          default: 20x4
          options: 
            - 20x4
            - 10x2
            - 5x1

jobs:
  hyp3-isce2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'relativeorbit/hyp3-isce2'
            ref: 'denseoffsets'

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      - name: Development install
        run: pip install -e .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Get Bucket Prefix
        env:
          REF: ${{ inputs.reference }}
          SEC: ${{ inputs.secondary }}
        run: |
          PREFIX=${REF:14:8}_${SEC:14:8}
          echo "PREFIX=${PREFIX}" >> $GITHUB_ENV

      - name: Run Hyp3-ISCE2
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
          ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
          ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
        run: |
          python -m hyp3_isce2 ++process insar_tops_burst \
            {{ inputs.reference }}  \
            ${{ inputs.secondary }}  \
            --looks ${{ inputs.nlooks }} \
            --apply-water-mask False \
            #--bucket fufiters \
            #--bucket-prefix $PREFIX

      # - name: Create STAC Metadata
      #   run: |
      #     python create_stac_item.py 
      
      - name: Upload to AWS S3
        run: | 
          OUTDIR=`ls -d S1_*`
          aws s3 sync $OUTDIR s3://fufiters/offsets/$PREFIX/$OUTDIR

      # - name: Upload to GitHub Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.PREFIX }}
      #     path: S1*.zip